# Generated by Django 3.0.6 on 2020-05-17 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('realtors', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='realtors',
            old_name='hore_date',
            new_name='hire_date',
        ),
    ]
